Traceback (most recent call last):
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import veloxchem as vlx

avail_funcs = vlx.available_functionals()

print('Available functionals:\n')

for i in range(0, len(avail_funcs), 8):
    print(', '.join(avail_funcs[i:i + 8]))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mveloxchem[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mvlx[39;00m
[1;32m      3[0m avail_funcs [38;5;241m=[39m vlx[38;5;241m.[39mavailable_functionals()
[1;32m      5[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mAvailable functionals:[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m)

File [0;32m~/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/__init__.py:26[0m
[1;32m      1[0m [38;5;66;03m#[39;00m
[1;32m      2[0m [38;5;66;03m#                              VELOXCHEM[39;00m
[1;32m      3[0m [38;5;66;03m#         ----------------------------------------------------[39;00m
[0;32m   (...)[0m
[1;32m     24[0m 
[1;32m     25[0m [38;5;66;03m# C++ classes[39;00m
[0;32m---> 26[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mveloxchemlib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m AtomBasis
[1;32m     27[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mveloxchemlib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m BasisFunction
[1;32m     28[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mveloxchemlib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m OverlapDriver

[0;31mImportError[0m: dlopen(/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/veloxchemlib.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libgfortran.5.dylib
  Referenced from: <CAA510D4-816A-34E5-9021-485EF5D56159> /Users/panor/miniconda3/envs/echem/lib/libopenblas.0.dylib
  Reason: tried: '/Users/panor/miniconda3/envs/echem/lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/bin/../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/bin/../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache)Library not loaded: @rpath/libgfortran.5.dylib
  Referenced from: <C6991033-5FD1-3ED0-9244-DFF142EB9D6C> /Users/panor/miniconda3/envs/echem/lib/libxtb.6.dylib
  Reason: tried: '/Users/panor/miniconda3/envs/echem/lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/lib/python3.12/site-packages/veloxchem/../../../libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/bin/../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/Users/panor/miniconda3/envs/echem/bin/../lib/libgfortran.5.dylib' (duplicate LC_RPATH '@loader_path'), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache)

